<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Wryco.EFirst</PackageId>
    <PackageVersion>1.0.2</PackageVersion>
    <Authors>ramity</Authors>
    <Company>Wryco</Company>
    <Description>An entity first design pattern. Simply extend base classes.</Description>
    <PackageDescription>An entity first design pattern. Simply extend base classes.</PackageDescription>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://wryco.com/EFirst</PackageProjectUrl>
    <RepositoryUrl>https://github.com/wryco/EFirst</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>PACKAGE-README.md</PackageReadmeFile>
    <PackageTags>QOL; Extension; Boilerplate; Base</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <DevelopmentDependency>false</DevelopmentDependency>
    <IsTool>false</IsTool>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="PACKAGE-README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>
