name: Nuget Publish
on:
  workflow_dispatch:
jobs:
  pre_clean:
    name: pre_clean
    runs-on: self-hosted
    container:
      image: alpine
    steps:
      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
  build:
    name: build
    runs-on: self-hosted
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    environment: production
    needs: pre_clean
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Docker compose build
        run: ./scripts/docker_build.sh
        shell: bash
      - name: Docker compose up
        run: ./scripts/docker_up.sh
        shell: bash
      - name: ASP.NET build
        run: docker exec efirst_aspnet sh -c "dotnet pack"
        shell: bash
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: NuGet push
        run: docker exec efirst_aspnet sh -c "dotnet nuget push bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json"
      - name: Docker compose down
        run: ./scripts/development/docker_down.sh
        shell: bash
  post_clean:
    name: post_clean
    runs-on: self-hosted
    container:
      image: alpine
    needs: build
    steps:
      - name: Cleanup workspace
        if: always()
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
